language: generic
addons:
  apt:
    packages:
      - tcl
      - tcllib

before_install:
  - git clone --depth=1 --branch=master https://github.com/lawrencewoodman/installmodule_tcl.git
  - sudo tclsh installmodule_tcl/installmodule.tcl vendor/xproc*.tm
  - chmod +x examples/run_examples.sh

script:
  # Run the tests
  - tclsh tests/all.tcl
  - examples/run_examples.sh
